<div class="jumbotron">
    <h1>Product Category / Create</h1>
</div>

<div class="row">

    <div class="col-md-8 col-md-offset-2">
        <form method="POST">
            <div class="form-group">
                <label class="control-label">Nombre</label>
                <input class="form-control" type="text" name="name"/>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary"> Crear</button>
            </div>
        </form>
    </div>
</div>
